FROM postgres:12.10
LABEL maintainer="Victor_Vedeneev@epam.com" org.label-schema.description="Database for docker homework"
ENV POSTGRES_PASSWORD="django"
ENV POSTGRES_USER="django"
ENV POSTGRES_DB="django"
ENV PGDATA="/var/lib/postgresql/data/pgdata"
EXPOSE 5432

HEALTHCHECK --interval=10s --timeout=5s --start-period=30s --retries=5 CMD pg_isready -U django -d django