FROM node:16 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM node:16-alpine3.15
LABEL maintainer="Victor_Vedeneev@epam.com" org.label-schema.description="Frontend for docker homework, developed with nodejs and react"
RUN apk add --no-cache curl
RUN npm install -g serve
COPY --from=build /app/build .
EXPOSE 3000
HEALTHCHECK --interval=10s --timeout=5s --start-period=30s --retries=5 CMD curl --fail http://localhost:3000 || exit 1  
USER node
CMD ["serve", "-s"]